apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: exapp
  name: exapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: exapp
  template:
    metadata:
      labels:
        run: exapp
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/core-demos/exapp/exapp:latest
        name: exapp
        ports:
        - containerPort: 8000
